# Generated by Django 4.1 on 2022-09-29 08:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "shipment_number",
                    models.UUIDField(default=uuid.uuid4, editable=False),
                ),
                ("loading_point", models.CharField(max_length=64)),
                ("unloading_point", models.CharField(max_length=64)),
                ("create_date", models.DateTimeField(auto_now_add=True)),
                ("load_date", models.DateField()),
                ("unload_date", models.DateField()),
                (
                    "tracking_number",
                    models.UUIDField(default=uuid.uuid4, editable=False),
                ),
                ("status", models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                ("quantity", models.IntegerField()),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="orders.order",
                    ),
                ),
            ],
        ),
    ]
