# Generated by Django 4.1 on 2022-09-29 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_rename_create_date_order_created_date_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={"ordering": ["-created_date", "-updated_date"]},
        ),
        migrations.RenameField(
            model_name="order",
            old_name="updated_at",
            new_name="updated_date",
        ),
        migrations.AddField(
            model_name="item",
            name="created_date",
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="item",
            name="updated_date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
