# Generated by Django 4.1 on 2022-09-29 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_alter_order_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="name",
            field=models.CharField(default="Something", max_length=64),
            preserve_default=False,
        ),
    ]
